[build]
  command = "npm run build"
  publish = "build"

[context.production.environment]
  REACT_APP_API_URL = "https://54.172.234.3:8080"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 